# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbJ-c-LrOiEhHamH2b_J6P8XWn845lEX
"""

import streamlit as st
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os

DATA_PATH = os.path.join(os.path.dirname(__file__), "california_housing_train.csv")
df = pd.read_csv(DATA_PATH)
# Load dataset
df = pd.read_csv("california_housing_train.csv")

# Feature Engineering
df["rooms_per_household"] = df["total_rooms"] / df["households"]
df["bedrooms_per_room"] = df["total_bedrooms"] / df["total_rooms"]
df["population_per_household"] = df["population"] / df["households"]

features = [
    "housing_median_age",
    "total_rooms",
    "total_bedrooms",
    "population",
    "households",
    "median_income",
    "rooms_per_household",
    "bedrooms_per_room",
    "population_per_household"
]

X = df[features]
y = np.log1p(df["median_house_value"])

# Train model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

model = XGBRegressor(n_estimators=500, learning_rate=0.03, max_depth=4)
model.fit(X_train, y_train)

# Streamlit UI
st.title("🏠 House Price Prediction Dashboard")

st.write("Enter housing details to predict house value")

housing_age = st.slider("Housing Median Age", 1, 60, 20)
total_rooms = st.number_input("Total Rooms", 1, 10000, 2000)
total_bedrooms = st.number_input("Total Bedrooms", 1, 5000, 500)
population = st.number_input("Population", 1, 10000, 1000)
households = st.number_input("Households", 1, 5000, 300)
median_income = st.number_input("Median Income", 0.0, 20.0, 5.0)

# Derived features
rooms_per_household = total_rooms / households
bedrooms_per_room = total_bedrooms / total_rooms
population_per_household = population / households

input_data = np.array([[
    housing_age,
    total_rooms,
    total_bedrooms,
    population,
    households,
    median_income,
    rooms_per_household,
    bedrooms_per_room,
    population_per_household
]])

input_data = scaler.transform(input_data)

if st.button("Predict House Price"):
    prediction = model.predict(input_data)
    price = np.expm1(prediction[0])
    st.success(f"Estimated House Price: ${price:,.2f}")

